#!/usr/bin/env bash
# Installs nginx web server
CONFIG_FILE="/etc/nginx/sites-available/default"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
echo "Hello World" | sudo tee /var/html/index.html > /dev/null
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://twitter.com/tegbiye;
    }
}" | sudo tee $CONFIG_FILE > /dev/null
sudo service nginx restart
