#!/usr/bin/env bash
# Installs nginx web server
CONFIG_FILE="/etc/nginx/sites-available/default"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://twitter.com/tegbiye;
    }
    error_page 404 /404.html;
    location /404 {
     root /etc/nginx/html;
     internal;
    }
}" | sudo tee $CONFIG_FILE > /dev/null
sudo service nginx restart
