#!/usr/bin/env bash
# configures a new Ubuntu machine

# Install nginx on web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sudo sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

# Create a firts index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Add to the nginx configuration file a redirection to another page
FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
    sudo sed -i "42i $STRING" /etc/nginx/sites-available/default
fi

# Add to the nginx configuration file a error page 404
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /404.html;\n"
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
    sudo sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi

sudo service nginx restart
