#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update
sudo apt-get install haproxy=2.0.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web1 54.234.75.41:80 check
        server web2 54.209.162.252:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
