#!/usr/bin/env bash
#configure nginx server to listen for port 80
# remove the default nginx config
rm /etc/nginx/sites-enabled/default
# configure nginx to listen on port 80 of all the server’s active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
