#!/usr/bin/env bash
# This script displays to_infinity indefinitely
# with a sleep 2 in between I am invincible!!! 
# when receiving a SIGTERM signal

trap 'echo "I am invinsible!!!"' 15
while true; do
   echo "to infinity and beyond"
   sleep 2
done
