#!/usr/bin/env bash
# This is script display Best School 10 times with hi on 9th iter
i=0
while [ "$i" -lt 10 ]
do
    echo "Best School"
    if [ "$i" -eq 8 ]
    then
        echo "Hi"
    fi
    i=$((i + 1))   
done
i=$i
