#!/usr/bin/env bash
# This is script display 1 to 20
# displays 4 and bad luck from China
# displays 9 and then bad luck from Japan
# displays 17 and bad luck from Italy

i=1
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
        4)
	echo "bad luck from China"
        ;;
        9)
	echo "bad luck from Japan"
        ;;
        17)
	echo "bad luck from Italy"
        ;;
    esac

    i=$((i + 1))
done
i=$i
